#!/usr/bin/env bash
cd baseline/checkpointing/pmdk-checkpoint1
make clean 
cd ../../../
cd baseline/checkpointing/memcached-pmem-checkpointing/
make clean
cd ../../../
cd baseline/checkpointing/redis-NDP-chekpoint/
make clean
cd ../../../
cd baseline/checkpointing/pmemkv-bench-chekpointing/
make clean
cd ../../../

cd baseline/logging/pmdk
make clean 
cd ../../../
cd baseline/logging/memcached/
make clean
cd ../../../
cd baseline/logging/redis-NDP1-golden/
make clean
cd ../../../
cd baseline/logging/pmemkv-bench/
make clean
cd ../../../

cd nearpm/logging/pmdk
make clean
cd ../../../
cd nearpm/logging/memcached-pmem-NDP/
make clean
cd ../../../
cd nearpm/logging/redis/redis-NDP/
make clean
cd ../../../../
cd nearpm/logging/pmemkv-bench/
make clean
cd ../../../

cd nearpm/checkpointing/pmdk-checkpoint1
make clean
cd ../../../
cd nearpm/checkpointing/memcached-pmem-checkpointing/
make clean
cd ../../../
cd nearpm/checkpointing/redis-NDP-chekpoint/
make clean
cd ../../../
cd nearpm/checkpointing/pmemkv-bench-chekpointing/
make clean
cd ../../../

cd baseline/shadow/pmdk-sd
make clean
cd ../../../
cd baseline/shadow/memcached-pmem-sd/
make clean
cd ../../../
cd baseline/shadow/redis-NDP-sd/
make clean
cd ../../../
cd baseline/shadow/pmemkv-bench-sd/
make clean
cd ../../../

cd nearpm/shadow/pmdk-sd
make clean
cd ../../../
cd nearpm/shadow/memcached-pmem-sd/
make clean
cd ../../../
cd nearpm/shadow/redis-NDP-sd/
make clean
cd ../../../
cd nearpm/shadow/pmemkv-bench-sd/
make clean
cd ../../../

cd nearpmMDsync/logging/pmdk
make clean
cd ../../../
cd nearpmMDsync/logging/memcached-pmem-NDP/
make clean
cd ../../../
cd nearpmMDsync/logging/redis/redis-NDP/
make clean
cd ../../../../
cd nearpmMDsync/logging/pmemkv-bench/
make clean
cd ../../../

cd nearpmMDsync/checkpointing/pmdk-checkpoint1
make clean
cd ../../../
cd nearpmMDsync/checkpointing/memcached-pmem-checkpointing/
make clean
cd ../../../
cd nearpmMDsync/checkpointing/redis-NDP-chekpoint/
make clean
cd ../../../
cd nearpmMDsync/checkpointing/pmemkv-bench-chekpointing/
make clean
cd ../../../

cd nearpmMDsync/shadow/pmdk-sd
make clean
cd ../../../
cd nearpmMDsync/shadow/memcached-pmem-sd/
make clean
cd ../../../
cd nearpmMDsync/shadow/redis-NDP-sd/
make clean
cd ../../../
cd nearpmMDsync/shadow/pmemkv-bench-sd/
make clean
cd ../../../

